<?php
 // module/Users/view/users/users/add.phtml:

 $title = 'Registeröidy';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('users', array('action' => 'registry')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('user_name'));
 echo "<br/>";
 echo $this->formRow($form->get('user_pass'));
 echo "<br/>";
 echo $this->formRow($form->get('email'));
 echo "<br/>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();